Adds camera zoom
fangfufu/Linux-Fake-Background-Webcam pull request #176
Opened 2022-01-25 16:14 UTC by systematiccaos

Hi,

I love the fake-background-webcam and would like to contribute a little zoom-feature. :-)

Best

caos

2022-01-25 18:34 UTC, systematiccaos commented
Added another commit to support frame-skipping for the mask calculation. No argument will update the mask every 5 frames.

2022-01-25 20:53 UTC, fangfufu commented
You are duplicating the feature in here: 
https://github.com/fangfufu/Linux-Fake-Background-Webcam/pull/174

For each feature you add, please use a different commit. Alternatively, please amend the description of the pull request and state what you are proposing.

2022-01-25 20:59 UTC, fangfufu requested changes

2022-01-25 20:59 UTC, fangfufu commented on fake.py
> +        self.classifier = mp.solutions.selfie_segmentation.SelfieSegmentation(model_selection=1)
You are calling this function again unnecessarily.

2022-01-25 20:59 UTC, fangfufu commented on fake.py
> +        there is another version below (paddedzoom2)
Where is your second version? If you have a second version, perhaps consider to use a parameter to switch the behaviour?

2022-01-25 20:59 UTC, fangfufu commented on fake.py
> +        # print(f'centerX: {centerX}')
Excessive amount of comments.

2023-10-09 08:50 UTC, closed without merging

2023-10-09 08:51 UTC, fangfufu commented
Closing stale pull request